config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
  
  	get '/home', to: 'pages#home'

  	resources :cuisines, only: [:new, :create, :show]
  	resources :categories, only: [:new, :create, :show]

  devise_for :users
  
  resources :locations do
    resources :reviews
  	   member do
  		  post 'like'
  	   end
  end
  
end

app/models/cuisine.rb
# == Schema Information
#
# Table name: cuisines
#
#  id   :integer          not null, primary key
#  name :string
#

class Cuisine < ActiveRecord::Base
	validates :name, presence: :true, length: { minimum: 2, maximum: 25 }
	has_many :location_cuisines
	has_many :locations, through: :location_cuisines
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
	authorize_resource

	def show
		@cuisine = Cuisine.find(params[:id])
		@locations = @cuisine.locations.paginate(page: params[:page], per_page: 4)
	end

	def new
		@cuisine = Cuisine.new
	end

	def create
		@cuisine = Cuisine.new(cuisine_params)
		if @cuisine.save
			flash[:success] = "Cuisine created successfully"
			redirect_to locations_path
		else
			render 'new'
		end
	end

	private

	def cuisine_params
		params.require(:cuisine).permit(:name)
	end

end

app/views/cuisines/_cuisine.html.erb
<span class="quiet"><small><%= link_to cuisine.name, cuisine_path(cuisine) %> </small></span>

app/views/cuisines/new.html.erb
<%= render 'shared/page_title', title: "Create New Cuisine" %>

<%= render 'shared/errors', obj: @cuisine %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= simple_form_for @cuisine do |f| %>
      
      <%= f.input :name %>

      
      <%= f.submit 'New cuisine', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/cuisines/show.html.erb
<%= render 'shared/page_title', title: "Cuisine type: " + @cuisine.name %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to 'All locations', locations_path %>
  </li>
  <li>
    <%= link_to 'Restaurants', ' ' %>
  </li>
  <li>
    <%= link_to 'Bars', ' ' %>
  </li>
  <li>
    <%= link_to 'Clubs', ' ' %>
  </li>
</ul>

<%= will_paginate @locations %>

<% @cuisine.locations.each do |location| %>
  <div class="row">
    
    <div class="col-md-2">
      <section class="user_info center">
        
        <h5>Name: <%= location.name %></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      
      <h4><%= link_to location.name, location_path(location) %></h4>
      <p>Cuisine: <%= render location.cuisines %></p>
      <p>
        <span class="quiet"><small>Created: <%= time_ago_in_words(location.created_at) %> ago, </small></span>
        <span class="quiet"><small>Updated: <%= time_ago_in_words(location.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_location_path(location, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= location.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_location_path(location, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= location.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-4">
      <%= image_tag(location.picture.url, size: "250x150", class: "gravatar") if location.picture? %>
    </div>
    
  </div>
  <hr/>
<% end %>

<%= will_paginate @locations %>