config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
  
  	get '/home', to: 'pages#home'

  	resources :cuisines, only: [:new, :create, :show]
  	resources :categories, only: [:new, :create, :show]

  devise_for :users
  
  resources :locations do
    resources :reviews
  	   member do
  		  post 'like'
  	   end
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_location
	before_action :find_review, only: [:edit, :update, :destroy]

	def show

	end

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.location_id = @location.id
		@review.user_id = current_user.id

		@review.rating = (@review.food + @review.ambience + @review.service + @review.value)/4.to_f

		if @review.save
			flash[:success] = "Your review and rating was added successful"
			redirect_to location_path(@location)
		else
			flash[:danger] = "Sorry, your review was not added"
			render 'new'
		end
	end

	def edit

	end

	def update

		@review.rating = (@review.food + @review.ambience + @review.service + @review.value)/4.to_f

		if @review.update(review_params)
			
			flash[:success] = "Your review was updated"
			redirect_to location_path(@location)
		else
			flash[:danger] = "Sorry, something was wrong"
			render 'edit'
		end
	end

	def destroy
		@review.destroy
    	redirect_to location_path(@location)
	end

	private

		def review_params
			params.require(:review).permit(:rating,
										:food,
										:ambience,
										:service,
										:value,
										:comment)
		end

		def find_location
			@location = Location.friendly.find(params[:location_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/views/reviews/_form.html.erb
<%= render 'shared/errors', obj: @review %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">

<%= simple_form_for([@location, @location.reviews.build]) do |f| %>
	<label>Food</label>
	<div id="food-form">
		
	</div>

	<label>Ambience</label>
	<div id="ambience-form">
		
	</div>

	<label>Service</label>
	<div id="service-form">
		
	</div>

	<label>Value</label>
	<div id="value-form">
	
	</div>
	<%= f.input :comment %>
	<%= f.submit 'Add Review', class: "btn btn-success" %>
<% end %>

</div>
</div>

<script>
	$('#food-form').raty('destroy');
		$('#food-form').raty({
			path: '/assets/',
			scoreName: 'review[food]'
		});
</script>

<script>
	$('#ambience-form').raty('destroy');
		$('#ambience-form').raty({
			path: '/assets/',
			scoreName: 'review[ambience]'
		});
</script>

<script>
	$('#service-form').raty('destroy');
		$('#service-form').raty({
			path: '/assets/',
			scoreName: 'review[service]'
		});
</script>

<script>
	$('#value-form').raty('destroy');
		$('#value-form').raty({
			path: '/assets/',
			scoreName: 'review[value]'
		});
</script>

app/views/reviews/_review.html.erb
<div class="well">

	<p>Overall Rating</p><div class="review-rating" data-score="<%= review.rating %>"></div><br>
	<p>Food</p><div class="review-rating" data-score="<%= review.food %>"></div><br>
	<p>Ambience</p><div class="review-rating" data-score="<%= review.ambience %>"></div><br>
	<p>Service</p><div class="review-rating" data-score="<%= review.service %>"></div><br>
	<p>Value</p><div class="review-rating" data-score="<%= review.value %>"></div><br>
	

	<% if review.created_at == review.updated_at %>
		<p><strong>Created at:</strong> <%= review.created_at.strftime("%d/%m/%Y") %></p>
	<% else %>
		<p><strong>Updated at:</strong> <%= review.updated_at.strftime("%d/%m/%Y") %></p>
	<% end %>

	
	<p><strong>Comment:</strong> <%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
	
		<div class="links btn-group">
		
			<%= link_to "Edit", edit_location_review_path(review.location, review), class: "btn btn-default" %>
			<%= link_to "Delete", location_review_path(review.location, review), method: :delete, data: { confirm: "Are you Sure" }, class: "btn btn-danger" %>
			
		</div>
	
		<% end %>

	<% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'shared/page_title', title: "Edit Review" %>

<%= render 'shared/errors', obj: @review %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">


<div class="edit-review-form">
<%= simple_form_for([@location, @review]) do |f| %>

	<label>Food</label>
	<div id="food-form">
		
	</div>

	<label>Ambience</label>
	<div id="ambience-form">
		
	</div>

	<label>Service</label>
	<div id="service-form">
		
	</div>

	<label>Value</label>
	<div id="value-form">

	</div>
	
	<%= f.input :comment %>
	<%= f.submit 'Edit Review', class: "btn btn-success" %>
<% end %>
</div>

</div>
</div>

<script>
	$('#food-form').raty('destroy');
		$('#food-form').raty({
			path: '/assets/',
			scoreName: 'review[food]'
		});
</script>

<script>
	$('#ambience-form').raty('destroy');
		$('#ambience-form').raty({
			path: '/assets/',
			scoreName: 'review[ambience]'
		});
</script>

<script>
	$('#service-form').raty('destroy');
		$('#service-form').raty({
			path: '/assets/',
			scoreName: 'review[service]'
		});
</script>

<script>
	$('#value-form').raty('destroy');
		$('#value-form').raty({
			path: '/assets/',
			scoreName: 'review[value]'
		});
</script>

app/views/reviews/new.html.erb
<%= render 'shared/page_title', title: "New Review" %>

<%= render 'shared/errors', obj: @review %>

<div class="new-review-form">

<%= render 'form' %>

</div>