config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
  
  	get '/home', to: 'pages#home'

  	resources :cuisines, only: [:new, :create, :show]
  	resources :categories, only: [:new, :create, :show]

  devise_for :users
  
  resources :locations do
    resources :reviews
  	   member do
  		  post 'like'
  	   end
  end
  
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#  picture     :string
#  user_id     :integer
#
# Indexes
#
#  index_locations_on_slug  (slug) UNIQUE
#

class Location < ActiveRecord::Base

  belongs_to :user
  has_many :likes
  has_many :location_cuisines
  has_many :cuisines, through: :location_cuisines
  has_many :location_categories
  has_many :categories, through: :location_categories
  has_many :reviews
	
	extend FriendlyId
  	friendly_id :name, use: :slugged

  mount_uploader :picture, PictureUploader
  validate :picture_size

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  	private

  	def picture_size
  		if picture.size > 3.megabytes
  			errors.add(:picture, "Should be less than 3MB")
  		end
  	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  authorize_resource
  before_action :set_location, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.paginate(:page => params[:page], :per_page => 12)
    
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = current_user.locations.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    like = Like.create(like: params[:like], user: current_user, location: @location)
    if like.valid?
      flash[:success] = "Your selection was succesfull"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike location once"
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, 
                                      :description, 
                                      :picture,
                                      cuisine_ids: [],
                                      category_ids: [])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= render 'shared/errors', obj: @location %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= simple_form_for(@location, html: { multipart: true }) do |f| %>
      
      <%= f.input :name %>
      
      
      <%= f.input :description, as: :text %>

    <%= f.association :cuisines,   as: :check_boxes %>

    <%= f.association :categories,   as: :check_boxes %>

      
      
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit(@location.new_record? ? 'Create Location' : 'Edit Location', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  
  $('#location_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB.Please choose a smaller file');
    }
  });
  
</script>

app/views/locations/edit.html.erb
<%= render 'shared/page_title', title: "Edit Location" %>

<%= render 'form' %>

app/views/locations/index.html.erb
<%= render 'shared/page_title', title: "All Locations" %>

<ul class="nav nav-tabs">
<li><%= link_to 'All locations', locations_path %></li>
  <% Category.all.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
  
</ul>

<%= will_paginate %>

<% @locations.each do |location| %>
  <div class="row">
    
    <div class="col-md-2">
      <section class="user_info center">
        
        <h5>Name: <%= location.name %></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      
      <h4><%= link_to location.name, location_path(location) %></h4>
      <% if location.cuisines.any? %>
        <p>Cuisine: <%= render location.cuisines %></p>
      <% end %>
      <% if location.categories.any? %>
        <p>Location Type: <%= render location.categories %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created: <%= time_ago_in_words(location.created_at) %> ago, </small></span>
        <span class="quiet"><small>Updated: <%= time_ago_in_words(location.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_location_path(location, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= location.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_location_path(location, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= location.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-4">
      <%= image_tag(location.picture.url, size: "250x150", class: "gravatar") if location.picture? %>
    </div>
    
  </div>
  <hr/>
<% end %>

<%= will_paginate %>

app/views/locations/new.html.erb
<%= render 'shared/page_title', title: "Create New Location" %>

<%= render 'form' %>

app/views/locations/show.html.erb
<%= render 'shared/page_title', title: @location.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <p>
      
    </p>
  </div>
  <div class="col-md-8">
      <%= link_to "Edit Location", edit_location_path(@location), class: "btn btn-success pull-right" if can? :update, @location %>
    
    <div class="show_location">
      <%= image_tag(@location.picture.url, size: "250x150", class: "gravatar") if @location.picture? %>
    </div>
    <p>Cuisine: <%= render @location.cuisines %></p>
    <p>Location type: <%= render @location.categories %></p>
    <h5 class="avg-rating">Average Rating</h5>
    <div class="average-review-rating" data-score=<%= @location.reviews.average(:rating) %>></div>
    <%= link_to 'Add Review', new_location_review_path(@location) %>
    <div class="well">
      <p>
        <strong>Description: </strong>
      </p>
      <%= simple_format(@location.description) %>
      <div class="pull-right">
        <%= link_to like_location_path(@location, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @location.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_location_path(@location, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @location.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render @location.reviews %>

<h5><%= link_to "Return to Locations", locations_path, class: "btn btn-warning btn-small" %></h5>

<script>
$('.review-rating').raty('destroy');
  $('.review-rating').raty({
    readOnly: true,
    number: 5,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
$('.average-review-rating').raty('destroy');
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>