config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
  
  	get '/home', to: 'pages#home'

  	resources :cuisines, only: [:new, :create, :show]
  	resources :categories, only: [:new, :create, :show]

  devise_for :users
  
  resources :locations do
    resources :reviews
  	   member do
  		  post 'like'
  	   end
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 margin-b-30">
                        <img class="margin-b-20" src="assets/images/logo-light.png" alt="">
                        <p>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                        </p>
                        <h5><a href="#">Read More...</a></h5>
                    </div>
                    <div class="col-md-3 margin-b-30">
                        <h3>Recent Posts</h3>
                        <ul class="list-unstyled recent-post">
                            <li class="clearfix">
                                <a href="#">
                                    <img src="assets/images/a1.jpg" alt="" width="70">
                                </a>
                                <div class="post-content">
                                    <h5><a href="#">Pizza cordoin lorem ipsum dolor sit amet</a></h5>
                                    <span>14 April 2016</span>
                                </div>
                            </li>
                            <li class="clearfix">
                                <a href="#">
                                    <img src="assets/images/a2.jpg" alt="" width="70">
                                </a>
                                <div class="post-content">
                                    <h5><a href="#">Cordoin lorem ipsum dolor sit amet</a></h5>
                                    <span>14 April 2016</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 margin-b-30">
                        <h3>Opening hours</h3>
                        <p><span class="text-color">Monday: </span>Closed</p>
                        <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                        <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                        <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p>
                    </div>
                    <div class="col-md-3 margin-b-30">
                        <h3>Contact Us</h3>
                        <p class="lead">
                            Ipsum Street, Lorem Tower, MO, Columbia, 302012
                        </p>
                        <p class="lead"><a href="#">+01 1800 100 1000</a></p>
                        <p><a href="#">info@resto.com</a></p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <ul class="list-inline f-social">
                            <li><a href="#"><i class="ion-social-facebook"></i></a></li>
                            <li><a href="#"><i class="ion-social-twitter"></i></a></li>
                            <li><a href="#"><i class="ion-social-linkedin"></i></a></li>
                            <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
                            <li><a href="#"><i class="ion-social-instagram"></i></a></li>
                        </ul>
                        <span>&copy; Copyright 2017. Resto</span>
                    </div>
                </div>
            </div>
        </footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-default sticky-header">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Cottyto', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Locations', locations_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cuisines <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Cuisine.all.each do |cuisine| %>
              <li><%= link_to cuisine.name, cuisine_path(cuisine) %></li>
            <% end %>
            <% if can? :create, Cuisine %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Cuisine", new_cuisine_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Locations">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="active"><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= render 'pages/jumbotron' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cottyto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

<script>
            jQuery(document).ready(function () {
                jQuery("#slider1").revolution({
                    sliderType: "standard",
                    jsFileLocation: "../../revolution/js/",
                    sliderLayout: "fullscreen",
                    dottedOverlay: "none",
                    delay: 9000,
                    navigation: {
                        arrows: {enable: true}
                    },
                    parallax: {
                        type: "on",
                        levels: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85],
                        origo: "enterpoint",
                        speed: 400,
                        bgparallax: "on",
                        disable_onmobile: "off"
                    },
                    gridwidth: 1170,
                    gridheight: 600
                });
            });
        </script>

</body>
</html>